# Generated by Django 5.2.14 on 2026-05-14 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Outfit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occasion', models.CharField(max_length=50)),
                ('mood', models.CharField(max_length=50)),
                ('recommendation', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='User', max_length=100)),
                ('skin_tone', models.CharField(max_length=50)),
                ('skin_type', models.CharField(max_length=50)),
                ('body_type', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skin_tone', models.CharField(max_length=50)),
                ('skin_type', models.CharField(max_length=50)),
                ('body_type', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OutfitHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occasion', models.CharField(max_length=100)),
                ('profession', models.CharField(blank=True, max_length=100)),
                ('mood', models.CharField(max_length=100)),
                ('colors_used', models.CharField(max_length=200)),
                ('outfit_json', models.TextField()),
                ('location', models.CharField(blank=True, max_length=100)),
                ('temperature', models.FloatField(null=True)),
                ('condition', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.profile')),
            ],
        ),
        migrations.CreateModel(
            name='WardrobeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('color', models.CharField(max_length=100)),
                ('fabric', models.CharField(max_length=100)),
                ('occasion', models.CharField(max_length=100)),
                ('season', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=100)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.profile')),
            ],
        ),
        migrations.CreateModel(
            name='WeatherLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('temperature', models.FloatField()),
                ('condition', models.CharField(max_length=100)),
                ('humidity', models.FloatField()),
                ('wind_speed', models.FloatField()),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.profile')),
            ],
        ),
    ]
