# Generated by Django 6.0.3 on 2026-04-23 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='User', max_length=100)),
                ('skin_tone', models.CharField(max_length=50)),
                ('skin_type', models.CharField(max_length=50)),
                ('body_type', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
            ],
        ),
    ]
