# Generated by Django 5.2.14 on 2026-05-18 11:22

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('skin_tone', models.CharField(max_length=100)),
                ('body_type', models.CharField(max_length=100)),
                ('skin_type', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=50)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile_images/')),
            ],
        ),
        migrations.CreateModel(
            name='WardrobeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=100)),
                ('style_type', models.CharField(default='casual', max_length=50)),
                ('color_name', models.CharField(default='', max_length=60)),
                ('color_hex', models.CharField(default='#000000', max_length=7)),
                ('image', models.ImageField(blank=True, null=True, upload_to=core.models.wardrobe_upload_path)),
                ('color', models.CharField(default='', max_length=100)),
                ('fabric', models.CharField(default='', max_length=100)),
                ('occasion', models.CharField(default='', max_length=100)),
                ('season', models.CharField(default='', max_length=50)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OutfitHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occasion', models.CharField(max_length=100)),
                ('profession', models.CharField(blank=True, max_length=100)),
                ('mood', models.CharField(max_length=100)),
                ('colors_used', models.CharField(max_length=200)),
                ('outfit_json', models.TextField()),
                ('location', models.CharField(blank=True, max_length=100)),
                ('temperature', models.FloatField(null=True)),
                ('condition', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='WeatherLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('temperature', models.FloatField()),
                ('condition', models.CharField(max_length=100)),
                ('humidity', models.FloatField()),
                ('wind_speed', models.FloatField()),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.userprofile')),
            ],
        ),
    ]
