# Generated by Django 5.2.14 on 2026-05-16 07:24

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Outfit',
        ),
        migrations.RemoveField(
            model_name='wardrobeitem',
            name='profile',
        ),
        migrations.AddField(
            model_name='wardrobeitem',
            name='color_hex',
            field=models.CharField(default='#000000', max_length=7),
        ),
        migrations.AddField(
            model_name='wardrobeitem',
            name='color_name',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AddField(
            model_name='wardrobeitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.wardrobe_upload_path),
        ),
        migrations.AddField(
            model_name='wardrobeitem',
            name='style_type',
            field=models.CharField(default='casual', max_length=50),
        ),
        migrations.AlterField(
            model_name='wardrobeitem',
            name='color',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='wardrobeitem',
            name='fabric',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='wardrobeitem',
            name='occasion',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='wardrobeitem',
            name='season',
            field=models.CharField(default='', max_length=50),
        ),
    ]
