# Generated by Django 6.0.3 on 2026-05-08 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Outfit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occasion', models.CharField(max_length=50)),
                ('mood', models.CharField(max_length=50)),
                ('recommendation', models.TextField()),
            ],
        ),
    ]
