# Generated by Django 5.2.14 on 2026-05-16 12:36

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_delete_outfit_remove_wardrobeitem_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wardrobeitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.wardrobe_upload_path),
        ),
    ]
