# Generated by Django 6.0.3 on 2026-05-18 04:48

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_wardrobeitem_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wardrobeitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.wardrobe_upload_path),
        ),
    ]
